<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <?=$this->headTitle('zend-expressive')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }

        body {
            background-color: #fff;
            color: #4C4C4C;
            font-family: Verdana, Geneva, sans-serif;
        }

        a,
        a:hover,
        a:focus {
            color: #923223;
        }

        .container {
        }

        .side-content {
            width: 40%;
            height: 100%;
            background: #fff;
        }

        .navigation {
            padding: 0 25px;
            padding-top: 25px;
        }

        .navigation ul {
            list-style: none;
            display: flex;
            padding: 0;
            margin: 0;
        }

        .navigation ul li {
            margin-right: 25px;
            border: 3px solid #000;
            transition: 200ms ease-in;
        }

        .navigation ul li:hover {
            background: #000;
        }

        .navigation ul li:hover a {
            color: #fff;
        }

        .navigation a {
            display: inline-block;
            padding: 5px 10px;
            color: #000;
            transition: 200ms ease-in;
        }

        .navigation a:hover {
            text-decoration: none;
        }

        .title-banner-container {
            position: relative;
            padding: 25px;
        }

        .title-banner {
            margin-bottom: 15px;
        }

        .title-banner > span {
            display: inline-block;
            background: #000;
            padding: 10px 30px;
            font-size: 26px;
            text-transform: uppercase;
            color: #fff;
        }

        .title-banner a {
            color: #fff;
        }

        .intro {
            padding: 25px;
            text-align: center;
        }

        .intro h2 {
            margin-bottom: 35px;
        }

        .section {
            width: 100vw;
            padding: 25px;
            background: #fff;
        }

        .section--full {
            position: relative;
            min-height: 100vh;
            background: none;
            margin-bottom: 0;
            padding: 0;
        }

        .section--full::before {
            content: '';
            position: absolute;
            z-index: -1;
            top: 0;
            right: 0;
            bottom: 0;
            width: 60%;
            background-color: #fff;
            background-image: url('/img/gongfu.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }

        .align-center {
            text-align: center;
        }

        h2 {
            text-align: center;
            text-transform: uppercase;
            margin-bottom: 55px;
            font-weight: bold;
        }

        h2 span {
            border-bottom: 2px solid #000;
            padding: 20px 20px 5px;
        }

        h3 {
            text-align: center;
            margin-bottom: 15px;
        }

        .events {
            display: flex;
            margin-top: 35px;
            justify-content: center;
        }

        .event {
            width: 50%;
            margin: 0 10px;
            padding: 15px 15px 25px;
        }

        .event p {
            text-align: justify;
        }

        .event__thumb {
            overflow: hidden;
            width: 250px;
            height: 250px;
            margin: 0 auto;
            margin-bottom: 25px;
            border-radius: 50%;
            border: 1px solid #403f3f;
        }

        .event__thumb img {
            width: 100%;
            height: 100%;
        }

        .event:first-child {
            margin-left: 0;
        }

        .event:last-child {
            margin-right: 0;
        }

        .event__price span,
        .event__time span {
            font-weight: bold;
        }

        .register-form {
            background: #f5f5f5;
            padding: 25px 35px;
        }

        .register-form form {
            display: flex;
            flex-flow: row wrap;
        }

        .input-error {
            border: 1px solid #923223;
        }

        .form_element {
            width: 50%;
            padding-right: 20px;
            margin-bottom: 30px;
        }

        .form_element--submit {
            display: flex;
            flex-flow: row-reverse;
            width: 100%;
        }

        .form_element label {
            font-weight: bold;
        }

        input,
        select {
            display: block;
        }

        input[type="text"],
        input[type="email"],
        select {
            width: 100%;
            padding: 10px 15px;
        }

        input[type="submit"],
        .button {
            display: inline-block;
            outline: none;
            padding: 15px 35px;
            background: transparent;
            border: 4px solid #4c4c4c;
            text-transform: uppercase;
            cursor: pointer;
            transition: 200ms ease-in;
            color: #000;
        }

        input[type="submit"]:hover,
        .button:hover,
        .button:focus {
            background: #656464;
            color: #fff;
            text-decoration: none;
        }

        .button--small {
            padding: 5px 15px;
            border-width: 2px;
        }

        .participate-button {
            margin-top: 10px;
        }

        .error-messages {
            padding: 0;
            margin: 0;
            list-style: none;
            color: #923223;
        }

        .error-messages li {
            margin-top: 5px;
        }

        @media only screen and (max-width: 800px) {
            h2 span {
                display: inline-block;
                padding: 0;
                padding-bottom: 5px;
                margin: 0 20px;
            }

            .container {
                max-width: 100%;
            }

            .section {
                padding: 15px;
            }

            .section--full {
                padding: 0;
            }

            .container {
                margin: 0;
                padding: 0;
            }

            .navigation {
                position: absolute;
                top: 0;
                right: 0;
                left: 0;
                padding: 10px 25px;
                margin: 0;
                background: #fff;
            }

            .section--full::before {
                display: block;
                position: relative;
                width: 100%;
                height: 33vh;
                background-position: center;
            }

            .side-content {
                width: 100%;
            }

            .events {
                flex-flow: row wrap;
            }

            .event {
                width: 100%;
                padding-right: 0;
                padding-left: 0;
                margin: 0;
            }

            .register-form {
                padding-left: 15px;
                padding-right: 15px;
            }

            .form_element {
                width: 100%;
                margin-right: 0;
                padding: 0;
            }

            label {
                margin: 0;
            }

            input[type="text"],
            input[type="email"],
            select {
                margin-top: 10px;
            }

            input[type="submit"],
            .button {
                width: 100%;
                text-align: center;
            }
        }
    </style>
</head>
<body class="app">
    <div class="app-content">
        <main>
            <?=$this->content?>
        </main>
    </div>

    <?=$this->inlineScript()?>
</body>
</html>
